### ISSUE TITLE
Would optional Sourcers be a welcome contribution?

### ISSUE THREAD

**Issue by stephenwithav** [ardanlabs/conf#12]
Optional ones for JSON, YAML, TOML, etc so coders can choose which Sourcers they want beyond `env` and `flag`?

They would be included in a `sources_extra.go` file.

**Comment by ardan-bkennedy** [comment]
Not in this repo because I don't want to pollute the need for 3rd part dependencies. I think these optional coders need to be provided in a different repo. I will probably need to look at the code again to see how that would be possible.

**Comment by stephenwithav** [comment]
Thanks for the clarification.

`Parse` uses an `Option` pattern, so it wouldn't be difficult.

**Comment by ardan-bkennedy** [comment]
But it could be cool to have code you can use in your own fork? Maybe a set of packages inside this module for the different options? If you don't use the import, if shouldn't be necessary.

**Comment by ardan-bkennedy** [comment]
```
// Parse parses configuration into the provided struct.
func Parse(args []string, namespace string, cfgStruct interface{}, sources ...Sourcer) error {

// Sourcer provides the ability to source data from a configuration source.
// Consider the use of lazy-loading for sourcing large datasets or systems.
type Sourcer interface {

	// Source takes the field key and attempts to locate that key in its
	// configuration data. Returns true if found with the value.
	Source(fld Field) (string, bool)
}
```

Anyone can write a sourcer so there could be a separate package that implements the interface. Dependency management would dictate a separate repo per sourcer or someone could write their own private one.

I could add a new repo called conf-sourcers that had separate packages and told people to just copy/paste code?

**Comment by stephenwithav** [comment]
That would work.  I created a local repo called `sourcers` that I'll add a few to over the next few days then push.

The goal is to ensure `conf` can read from everything Viper can.

**Comment by stephenwithav** [comment]
If you're curious.

https://github.com/stephenwithav/sourcers/

**Comment by ardan-bkennedy** [comment]
Send me an email so we can jump on a call. I have ideas.
