### ISSUE TITLE
Question: Using env vars without prefix

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [ardanlabs/conf#16]
Sorry in advance for opening a question as an issue, could not find a relevant community to direct this.

How can we use the env vars __without__ prefix?

When I pass the empty string as prefix:

```
if err := conf.Parse(os.Args[1:], "", &cfg); 
```

I get a leading underscore in the env vars generated

```
  --web-service-port/$_SERVICE_PORT                    <int>     (default: 8888)
```

This was previously defined in a `cfg` struct as follows

```
		Web struct {
			ServicePort int `conf:"default:98765,env:SERVICE_PORT"`
		}
```

**Comment by ardan-bkennedy** [comment]
I can make a code change to support this is an empty string is provided.

**Comment by ardan-bkennedy** [comment]
There is now version v1.4.0 that handles what you need.

**Comment by pantelis-karamolegkos** [comment]
💯  cool! Many thanks Bill.
