### ISSUE TITLE
FR: Mask instead of completely hiding noprint variable

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [ardanlabs/conf#18]
Instead of entirely omitting from printouts any variables set as `noprint` in the `cfg` struct, perhaps it would be a good idea just to omit / mask its value.

This would help the user/developer realise that **there is indeed** a configuration variable (set/expected) named (say) `AWS_SECRET_ACCESS_KEY` but it is sensitive. (it helps precision in terms of having the logs reflect __exactly__ (with the highest level of precision) the actual configuration.

**Comment by ardan-bkennedy** [comment]
There is a mask option. Look at the documentation.

**Comment by pantelis-karamolegkos** [comment]
Thanks 👍🏻 . Hence, no need for this issue
