### ISSUE TITLE
yaml parsing ignores field options like `required` 

### ISSUE THREAD

**Issue by Deichindianer** [ardanlabs/conf#21]
# Summary

The yaml package is registered as a `Parser` which fills the struct before it is passed into the `parse` function that evaluates all fields with the two sources:

* Environment
* Flags

During this they also check if the value has ever been provided, since the yaml parsing happens before the `parse` function during the `parser.Process` loop, the evaluation fails and you get the error that you did not provide a required field. Attaching a debugger and looking at the config struct throughout the flow of the `parse` function shows that the fields are set correctly by the yaml parser.

Not sure what the correct implementation would be here, it feels like that the yaml parsing should be a `Source` instead this would add some extra parameters to the API of `Parse` though to figure out where the config file is located to read it. 

# Steps to repoduce

Repository: https://github.com/Deichindianer/yaml-parse-error

```go
package main

import (
	"github.com/ardanlabs/conf/v2"
	"github.com/ardanlabs/conf/v2/yaml"
	"os"
)

type Config struct {
	RequiredKey bool `conf:"required" yaml:"required"`
}

func main() {
	var cfg Config

	f, err := os.ReadFile("./config.yml")
	if err != nil {
		panic(err)
	}

	_, err = conf.Parse("", &cfg, yaml.WithData(f))
	if err != nil {
		panic(err)
	}
}
```

This yields:

```sh
panic: parsing config: required field RequiredKey is missing value

goroutine 1 [running]:
main.main()
        /home/bp/Code/tmp/yaml-parse-error/main.go:23 +0xc5
exit status 2

```

**Comment by ardan-bkennedy** [comment]
It's very very complicated to make a sourcer for this, so I took this approach. I will look at the panic, but my guess is your config does not provide a value for this? It would be helpful to see your config.yaml file.

**Comment by ardan-bkennedy** [comment]
I have not forgotten about this. We should talk about this again as a refresher.

**Comment by Deichindianer** [comment]
Happy to have a chat or retrace the problem, probably best if you lead the questions that are open :)

**Comment by ardan-bkennedy** [comment]
```
// If this key is not provided by any source, check if it was
// required to be provided.
if !everProvided && field.Options.Required {
	return fmt.Errorf("required field %s is missing value", field.Name)
}
```

I am wondering if I don't do a check for non-zero value here?

**Comment by ardan-bkennedy** [comment]
Assuming this yaml file

```
required: true
```

I have a solution now. I will push it.

**Comment by ardan-bkennedy** [comment]
v3.1.1 is now available, please let me know if this works for you.

**Comment by ardan-bkennedy** [comment]
If this fixes the problem, please close the issue.

**Comment by Deichindianer** [comment]
Can confirm it fixes it :) Thanks for the patch!
