### ISSUE TITLE
no workflow in circleci while badge is green

### ISSUE THREAD

**Issue by Pavel-Durov** [ardanlabs/conf#29]
There is a [circleci config](https://github.com/ardanlabs/conf/blob/master/.circleci/config.yml) in the project, README [![CircleCI](https://circleci.com/gh/ardanlabs/conf.svg?style=svg)](https://circleci.com/gh/ardanlabs/conf) is green but looking at [circleci](https://app.circleci.com/pipelines/github/ardanlabs/conf) there are not workflows running.

Is it intentional?

**Comment by ardan-bkennedy** [comment]
Let me look at this.

**Comment by ardan-bkennedy** [comment]
Didn't realize how broken this was and for all my projects. Working now.
