### ISSUE TITLE
Parser ignores required option

### ISSUE THREAD

**Issue by martin-viggiano** [ardanlabs/conf#40]
# Summary

A Parser is used when parsing the configuration, which fills the config struct before it is passed to the parse function that evaluates flags and environment variables sources. The parse function checks if the value has been provided either by flags or environment variables but does not take in account values provided by Parsers.

If a field is marked as required, but its value is provided by a Parser and not overwritten by a flag or environment variable, an error will be raised.

Related to issue #21.

# Steps to reproduce

```go
package main

import (
	"github.com/ardanlabs/conf/v3"
	"github.com/ardanlabs/conf/v3/yaml"
)

func main() {
	var cfg struct {
		Value string `conf:"value,required" yaml:"value"`
	}

	var yamlData = "value: something\n"

	_, err := conf.Parse("", &cfg, yaml.WithData([]byte(yamlData)))
	if err != nil {
		panic(err)
	}
}
```

[Run in Go Playground](https://go.dev/play/p/vtVxmlZWuFU):

```console
panic: parsing config: required field Value is missing value

goroutine 1 [running]:
main.main()
	/tmp/sandbox3759184289/prog.go:17 +0xac

Program exited.
```

# Possible fix

We could check if the field has its zero value here:

https://github.com/ardanlabs/conf/blob/afcd88003cc5d782329668d5dce009981efa6f9f/conf.go#L233

```diff
-              if field.Options.Required && !foundOverride {
+              if field.Options.Required && field.Field.IsZero() && !foundOverride {
```

**Comment by ardan-bkennedy** [comment]
We can't mess with this. We recently added a new option `notzero` to handle this nuance. Required means a value must be provided through the parsing process. The `notzero` means the value just can't be set to it's zero value state.

Does the `notzero` option solve your problem?

**Comment by martin-viggiano** [comment]
You are right, this can be solved by using `notzero`.

Thanks!
