### ISSUE TITLE
Using namespace in variable when overriding variable name

### ISSUE THREAD

**Issue by roloum** [ardanlabs/conf#7]
Hey Bill, I was just curious.. when overriding a variable name, as in the following example:
```
type ip struct {
	Name string `conf:"default:localhost,env:IP_NAME_VAR"`
	IP   string `conf:"default:127.0.0.0"`
}
```

The package defines the variable using the namespace, as shown in the help options:
OPTIONS
  --ip-name/$CRUD_IP_NAME_VAR   <string>    (default: localhost)

Is that the desired behavior? Why doesn't it use the variable as defined when overridden: $IP_NAME_VAR ?
Thanks

**Comment by ardan-bkennedy** [comment]
This is the desired behavior. The prefix you specified (in this case `CRUD`) is always applied for consistency.

**Comment by gngchrs** [comment]
Hi @ardan-bkennedy, 

Question: This means there's no intention in supporting an empty namespace. Say `env = 'ENVIRONMENT'`, instead of `env = CRUD_ENVIRONMENT'`

**Comment by ardan-bkennedy** [comment]
Yea, and I believe this is important because you could be running multiple services on the same machine and you need to namespace one service over the other.
